# docker-compose.yml
version: "3.8"

services:
  panspace:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./indexes:/app/indexes
      - ./sequences:/app/sequences
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: panspace app